/* eslint-disable */
// @ts-nocheck
/** Ask-the-data engine, ported verbatim from the old ui_ask.js. `makeAnswer(ctx)` binds it to the dataset. */
import { fN, fP, fS, sum, addArr, esc } from '../../lib/format';
export interface Answer { t: string; cols?: any[]; rows?: any[]; go?: [string, string?] }
const HLG:any={f3:'lg3',f2:'lg2',f1:'lg1'};
function accOf(a:any,fc:any,mask:any,NH:number){let e=0,t=0,u=0,o=0;for(let i=0;i<NH;i++){if(a[i]==null||fc[i]==null||(mask&&mask[i]==null))continue;const d=fc[i]-a[i];e+=Math.abs(d);t+=a[i];d<0?u-=d:o+=d}return{acc:t?Math.max(0,1-e/t):null,bias:t?(o-u)/t:null,u,o,t}}
export function makeAnswer({D,W,NH,CATS,PM,nameOf,LABELS}:any){
const dlab=(i:number)=>LABELS[i];
const norm=s=>s.toLowerCase().replace(/[^a-z0-9₹ ]+/g,' ').replace(/\s+/g,' ').trim();
const STOP=new Set(['the','and','for','with','led','lights','light','of','a','in','what','how','is','are','by','to','on','at','all','hd','at','on','or','it','as','an','be','do','we','my','me','us','up','no','so','if','m1','m2','m3','w']);
function findProds(q){const nq=' '+norm(q)+' ',hits=[];D.prods.forEach(p=>{let sc=0;if(nq.includes(' '+p.id.replace(/-/g,' ')+' ')||nq.includes(' '+p.id+' '))sc+=5;const nn=norm(p.name);if(nq.includes(' '+nn+' '))sc+=6;nn.split(' ').forEach(w=>{if(w.length>=2&&!STOP.has(w)&&nq.includes(' '+w+' '))sc+=1});if(/npd.?0?(\d)/.test(nq)){const m=nq.match(/npd.?0?(\d)/);if(p.id==='npd0'+m[1])sc+=8}if(sc)hits.push([sc,p])});hits.sort((a,b)=>b[0]-a[0]);if(!hits.length)return[];const top=hits[0][0];return hits.filter(h=>h[0]>=top).map(h=>h[1]).slice(0,4)}
const findCat=q=>{const nq=norm(q);return CATS.find(c=>nq.includes(norm(c)))||CATS.find(c=>norm(c).split(' ').filter(w=>w.length>4&&!STOP.has(w)).some(w=>nq.includes(w)))};
const findDep=q=>{const nq=norm(q);return Object.entries(D.dep).find(([k,v])=>nq.includes(v.toLowerCase()))?.[0]};
const findHz=q=>/\b(m3|13)\b/.test(norm(q))?'f3':/\b(m2|9)\b/.test(norm(q))?'f2':/\b(m1|4)\b/.test(norm(q))?'f1':null;
function findYear(q){const m=q.match(/20(2[3-6])/);return m?+('20'+m[1]):null}
function seriesFor(id,lvl,depot,key){const o=[];if(lvl==='N')return D.nat[id][key].slice();(depot?[depot]:Object.keys(D.dep)).forEach(d=>addArr(o,D.kol[d+'|'+id][key]));return o}
function accFor(ids,lvl,depot,h,src){const a=[],f=[],m=[];ids.forEach(id=>{addArr(a,seriesFor(id,lvl,depot,'a'));addArr(f,seriesFor(id,lvl,depot,src==='sales'||h==='sb'?h:HLG[h]));addArr(m,seriesFor(id,lvl,depot,HLG[h==='sb'?'f3':h]))});return accOf(a,f,m,NH)}
const ans=(t:string,extra?:any)=>({t,...extra});
function answer(q:string):Answer|null{const nq=norm(q),ps=findProds(q),cat=findCat(q),dep=findDep(q),hz=findHz(q),yr=findYear(q),lvl=(dep||/kolkata/.test(nq))?'K':'N',has=r=>r.test(nq);
 const ids=ps.length?ps.map(p=>p.id):cat?D.prods.filter(p=>p.cat===cat).map(p=>p.id):null,lab=ps.length?ps.map(p=>p.name).join(', '):cat||'all products';
 /* quick commerce */
 if(has(/quick|\bqc\b|dark store|blinkit|zepto|instamart/)){const rows=Object.keys(D.qc).map(k=>{const q=D.qc[k];let t=0,o=0,s=0,ln=0,ot=0;for(let i=0;i<NH;i++){if(q.t[i]==null)continue;t+=q.t[i];o+=q.o[i];s+=q.s[i];ln+=q.ln[i];ot+=q.ot[i]}return{hub:k.split('|')[0],partner:k.split('|')[1],t,o,over:t?o/t:null,otif:ln?ot/ln:null}}).filter(r=>r.t>0);
  return ans(`Quick-commerce OTIF is <b>${fP(D.kpi.qc_otif)}</b> overall (judged against what the hub could allocate), and partners order about <b>${D.kpi.qc_over}×</b> true consumer demand. The table shows each partner × hub.`,{cols:[{k:'hub',l:'Hub'},{k:'partner',l:'Partner'},{k:'t',l:'True demand',n:1,f:v=>fN(v)},{k:'o',l:'Ordered',n:1,f:v=>fN(v)},{k:'over',l:'Over-order',n:1,f:v=>v.toFixed(2)+'×'},{k:'otif',l:'OTIF',n:1,f:v=>fP(v)}],rows,go:['chan','qc']})}
 /* replenishment OTIF */
 if(has(/otif|on time|in full|fill rate|replenish|truck|lead time/)){const R=D.rep,T=R.total;
  if(dep){const r=R.depot.find(x=>x.k===D.dep[dep]||x.k===dep);if(r)return ans(`<b>${D.dep[dep]}</b>: OTIF ${fP(r.otif)} (on time ${fP(r.on_time)}, in full ${fP(r.in_full)}), fill rate ${fP(r.fill)} across ${fN(r.n)} order lines. Network average OTIF is ${fP(T.otif)}.`,{go:['supply','repl']})}
  if(cat){const r=R.cat.find(x=>x.k===cat);if(r)return ans(`<b>${esc(cat)}</b>: OTIF ${fP(r.otif)} (on time ${fP(r.on_time)}, in full ${fP(r.in_full)}), fill ${fP(r.fill)}. Network average OTIF is ${fP(T.otif)}.`,{go:['supply','repl']})}
  const dl=Object.entries(R.delay).sort((a,b)=>b[1]-a[1]).slice(0,1)[0];
  return ans(`Network replenishment OTIF is <b>${fP(T.otif)}</b> (on time ${fP(T.on_time)}, in full ${fP(T.in_full)}), fill rate ${fP(T.fill)}, average lead time ${T.lead} weeks. Most common delay reason: <i>${esc(dl[0].replace(/^; /,''))}</i> (${fN(dl[1])} lines). By depot below.`,{cols:[{k:'k',l:'Depot'},{k:'n',l:'Lines',n:1,f:v=>fN(v)},{k:'otif',l:'OTIF',n:1,f:v=>fP(v)},{k:'on_time',l:'On time',n:1,f:v=>fP(v)},{k:'in_full',l:'In full',n:1,f:v=>fP(v)},{k:'fill',l:'Fill',n:1,f:v=>fP(v)}],rows:R.depot,go:['supply','repl']})}
 /* flags */
 if(has(/flag|challenge|unusual|outlier/)){const g=lvl,rows=D.rs.filter(r=>r[0]===g&&(!ids||ids.includes(r[1]))&&(!dep||r[2]===dep)&&(!yr||W[r[3]].startsWith(yr))),sales=rows.filter(r=>r[4]).length,sup=rows.filter(r=>r[5]).length;
  return ans(`For <b>${esc(lab)}</b>${dep?' at '+D.dep[dep]:g==='K'?' in Kolkata':' nationally'}${yr?' in '+yr:''} there are <b>${fN(sales)}</b> sales-forecast flags and <b>${fN(sup)}</b> procurement flags. Latest ones below.`,{cols:[{k:'week',l:'Week'},{k:'kind',l:'Type'},{k:'prod',l:'Product'},{k:'why',l:'Reason'}],rows:rows.map(r=>({week:W[r[3]],kind:r[4]?'Sales':'Procurement',prod:nameOf(r[1]),why:r[4]||r[5]})).sort((a,b)=>a.week<b.week?1:-1),go:['forecast']})}
 /* accuracy / rankings */
 if(has(/accura|forecast error|wape|bias|how good|worst|best/)&&!has(/launch|vapor|mosquito|month/)){const h=hz||'f3',hn={f3:'M3 (13 weeks ahead)',f2:'M2 (9 weeks ahead)',f1:'M1 (4 weeks ahead)'}[h];
  if(has(/worst|best|rank|lowest|highest|top|least|most|which (products|skus|items)/)){const pool=ids||D.prods.map(p=>p.id),rows=pool.map(id=>{const x=accFor([id],lvl,dep,h);return{name:nameOf(id),cat:PM[id].cat,acc:x.acc,bias:x.bias,units:x.t}}).filter(r=>r.acc!=null).sort((a,b)=>has(/best|highest/)?b.acc-a.acc:a.acc-b.acc);
   return ans(`${has(/best|highest/)?'Most':'Least'} accurate ${cat?'products in '+esc(cat):'products'} at ${hn} for LightGBM, ${dep?D.dep[dep]:lvl==='K'?'Kolkata':'national'}, 52-week backtest: <b>${esc(rows[0].name)}</b> at ${fP(rows[0].acc)}.`,{cols:[{k:'name',l:'Product'},{k:'cat',l:'Category'},{k:'acc',l:'Accuracy',n:1,f:v=>fP(v)},{k:'bias',l:'Bias',n:1,f:v=>fS(v)}],rows:rows.slice(0,10),go:['forecast']})}
  const pool=ids||D.prods.map(p=>p.id),rows=['f3','f2','f1','sb'].map(k=>{const n=accFor(pool,'N',null,k==='sb'?'f3':k,'lg'),kk=accFor(pool,'K',dep,k==='sb'?'f3':k,'lg'),ns=accFor(pool,'N',null,k,'sales'),ks=accFor(pool,'K',dep,k,'sales');return{h:{f3:'M3 · 13 wk',f2:'M2 · 9 wk',f1:'M1 · 4 wk',sb:'Seasonal baseline'}[k],n:k==='sb'?ns.acc:n.acc,nb:k==='sb'?ns.bias:n.bias,k:k==='sb'?ks.acc:kk.acc,kb:k==='sb'?ks.bias:kk.bias,ns:k==='sb'?null:ns.acc,ks:k==='sb'?null:ks.acc}}),hi=['f3','f2','f1'].indexOf(h),me=rows[hi];
  return ans(`LightGBM weekly accuracy for <b>${esc(lab)}</b> at ${hn}: <b>${fP(lvl==='K'?me.k:me.n)}</b> ${dep?'at '+D.dep[dep]:lvl==='K'?'in Kolkata':'nationally'}, vs ${fP(lvl==='K'?me.ks:me.ns)} for the sales forecast and ${fP(lvl==='K'?rows[3].k:rows[3].n)} for the seasonal baseline. Scored on the 52-week backtest.${ids?'':' Totals across all products, so higher than the per-product average on the Overview.'}`,{cols:[{k:'h',l:'Horizon'},{k:'n',l:'National (LightGBM)',n:1,f:v=>fP(v)},{k:'ns',l:'National (sales fcst)',n:1,f:v=>fP(v)},{k:'k',l:dep?D.dep[dep]+' (LightGBM)':'Kolkata (LightGBM)',n:1,f:v=>fP(v)},{k:'ks',l:'Kolkata (sales fcst)',n:1,f:v=>fP(v)}],rows,go:['forecast']})}
 /* stock / cover */
 if(has(/cover|stock out|stockout|safety stock|stock|inventory|overstock|over stock/)){const wk=NH-1,rows=[];Object.keys(D.dep).forEach(d=>{if(dep&&d!==dep)return;D.prods.forEach(p=>{if(ids&&!ids.includes(p.id))return;const K=D.kol[d+'|'+p.id];rows.push({dep:D.dep[d],prod:p.name,cover:K.w[wk],stock:K.cl[wk],ss:K.ss[wk]})})});
  const low=rows.filter(r=>r.cover!=null&&r.cover<.6),hi=rows.filter(r=>r.cover>3);const list=has(/\bover\b|excess|\bhigh\b|too much/)?hi:low;
  return ans(`As of ${dlab(wk)}${dep?' at '+D.dep[dep]:' across 5 depots'}: <b>${low.length}</b> depot × product lines are below 0.6 weeks of cover (stock-out risk) and <b>${hi.length}</b> are above 3 weeks (over-stocked). Showing ${list===hi?'over-stocked':'low-cover'} lines.`,{cols:[{k:'dep',l:'Depot'},{k:'prod',l:'Product'},{k:'cover',l:'Weeks cover',n:1,f:v=>v.toFixed(1)},{k:'stock',l:'Closing stock',n:1,f:v=>fN(v)},{k:'ss',l:'Safety stock',n:1,f:v=>fN(v)}],rows:list.sort((a,b)=>list===hi?b.cover-a.cover:a.cover-b.cover),go:['supply','cover']})}
 /* MOQ */
 if(has(/moq|price break|saving|discount|minimum order/)){const M=D.moq,cap=sum(M.src.map(r=>r.captured)),fg=sum(M.src.map(r=>r.foregone)),rows=M.prod.filter(r=>!ids||ids.includes(r.id));
  return ans(`Price-break savings captured: <b>₹${fN(cap)}</b>; foregone (lots that missed the break): <b>₹${fN(fg)}</b> — a capture rate of ${fP(cap/(cap+fg))} by value. ${sum(M.src.map(r=>r.missed))} of ${sum(M.src.map(r=>r.lots))} lots missed the break.`,{cols:[{k:'name',l:'Product'},{k:'moq',l:'MOQ',n:1,f:v=>fN(v)},{k:'brk',l:'Break qty',n:1,f:v=>fN(v)},{k:'disc',l:'Discount',n:1,f:v=>fP(v)},{k:'captured',l:'Captured ₹',n:1,f:v=>fN(v)},{k:'foregone',l:'Foregone ₹',n:1,f:v=>fN(v)}],rows:rows.sort((a,b)=>b.foregone-a.foregone).slice(0,10),go:['supply','moq']})}
 /* cannibalisation */
 if(has(/cannibal/)){const rows=D.ican.filter(r=>!ids||ids.includes(r.npd_id)||ids.includes(r.cannibalised_product_id));return ans(`Internal cannibalisation: the largest is <b>${esc(D.ican.slice().sort((a,b)=>b.national_units_lost_to_npd-a.national_units_lost_to_npd)[0].cannibalised_product)}</b> losing ${fN(Math.max(...D.ican.map(r=>r.national_units_lost_to_npd)))} units to a new launch. External competitor actions cost ${fN(sum(D.ecan.map(r=>r.national_units_lost)))} units across ${D.ecan.length} events.`,{cols:[{k:'npd',l:'New product'},{k:'cannibalised_product',l:'Cannibalised'},{k:'cannibalisation_rate_of_npd_volume',l:'Share of NPD vol',n:1,f:v=>fP(v,0)},{k:'national_units_lost_to_npd',l:'Units lost',n:1,f:v=>fN(v)}],rows:(rows.length?rows:D.ican),go:['newp','cannib']})}
 /* vaporizer */
 if(has(/vapori|mosquito|incumbent|refill/)){const sm=D.vsum.filter(r=>r.window==='all 26 weeks'&&r.geography==='National'),best=sm.slice().sort((a,b)=>b.accuracy_pct-a.accuracy_pct)[0];const k='National|Eveready mosquito vaporizer line',sh=D.vap[k].volume_share_pct,last=sh[NH-1];
  return ans(`For the Eveready mosquito vaporizer launch, the best 26-week national method was <b>${esc(best.method)}</b> at ${fP(best.accuracy_pct)} accuracy. The company plan overshot actuals by ${fS(sm[0].bias_pct,0)}. Eveready's latest volume share is ${fP(last)}.`,{cols:[{k:'method',l:'Method'},{k:'actual_units',l:'Actual',n:1,f:v=>fN(v)},{k:'forecast_units',l:'Forecast',n:1,f:v=>fN(v)},{k:'bias_pct',l:'Bias',n:1,f:v=>fS(v,0)},{k:'accuracy_pct',l:'Accuracy',n:1,f:v=>fP(v)}],rows:sm,go:['newp','launch']})}
 /* launches */
 if(has(/launch|npd|new product|best month|timing/)){const rr=D.npdr.filter(r=>!ids||ids.includes(r.product_id));
  if(has(/month|timing|when/)&&ps.length){const l=D.lt.filter(x=>x.product_id===ps[0].id).sort((a,b)=>a.rank_52wk-b.rank_52wk);return ans(`Best launch month for <b>${esc(ps[0].name)}</b> is <b>${l[0].launch_month}</b> (${fN(l[0].units_first_52wk)} units in 52 weeks); worst is ${l[l.length-1].launch_month} (${fN(l[l.length-1].units_first_52wk)}).`,{cols:[{k:'launch_month',l:'Month'},{k:'units_first_52wk',l:'52-wk units',n:1,f:v=>fN(v)},{k:'rank_52wk',l:'Rank',n:1},{k:'verdict',l:'Verdict'}],rows:l,go:['newp','timing']})}
  return ans(`${rr.length} launch${rr.length>1?'es':''} found. 13-week achievement vs budget ranges from ${fP(Math.min(...rr.map(r=>r.achievement_vs_budget_13wk)),0)} to ${fP(Math.max(...rr.map(r=>r.achievement_vs_budget_13wk)),0)}.`,{cols:[{k:'product',l:'Launch'},{k:'launch_date',l:'Launched'},{k:'launch_slip_weeks',l:'Slip (wk)',n:1},{k:'national_units_13wk',l:'13-wk units',n:1,f:v=>fN(v)},{k:'achievement_vs_budget_13wk',l:'vs budget',n:1,f:v=>fP(v,0)}],rows:rr,go:['newp','launch']})}
 /* influencer */
 if(has(/influencer|campaign/)){return ans(`Influencer campaigns lifted test depots by <b>${fS(Math.min(...D.inf.map(r=>r.influencer_lift_pct)),0)} to ${fS(Math.max(...D.inf.map(r=>r.influencer_lift_pct)),0)}</b> vs control depots (units per share point).`,{cols:[{k:'product',l:'Campaign'},{k:'influencer_lift_pct',l:'Lift',n:1,f:v=>fS(v,0)},{k:'incremental_units_test_depots',l:'Incremental units',n:1,f:v=>fN(v)},{k:'cost_per_incremental_unit_inr',l:'₹ / unit',n:1,f:v=>fN(v)}],rows:D.inf,go:['chan','inf']})}
 /* budget */
 if(has(/budget|financial year|\bfy\b|annual|target/)){const fy=(q.match(/fy ?-?(?:20)?(\d{2})/i)||[])[1],rows=D.budt.filter(b=>!fy||b.fy==='FY'+fy).map(b=>({fy:b.fy,budget:b.budget_cr,sales:sum(D.bud.filter(x=>x.fy===b.fy).map(x=>x.sales_cr))}));
  return ans(`Annual budget by financial year (₹ Cr). FY24 and FY27 are part-years within the data window.`,{cols:[{k:'fy',l:'FY'},{k:'budget',l:'Budget ₹ Cr',n:1,f:v=>fN(v,1)},{k:'sales',l:'Actual sales ₹ Cr',n:1,f:v=>fN(v,1)}],rows,go:['overview']})}
 /* festival / monsoon */
 if(has(/festival|puja|diwali|poila|eid|holi/)){const m=D.fest.filter(f=>(!yr||String(f.year)===String(yr))&&(!/durga|kali|diwali|poila|vishwa|eid|holi/.test(nq)||norm(f.festival).split(' ').some(w=>w.length>3&&nq.includes(w))));return ans(`${m.length} festival entries${yr?' in '+yr:''}.`,{cols:[{k:'festival',l:'Festival'},{k:'date',l:'Date'},{k:'scope',l:'Scope'},{k:'categories_lifted',l:'Categories lifted'}],rows:m.length?m:D.fest,go:['chan','fest']})}
 if(has(/monsoon|rain|delay/)){const sh=[];D.cal.shock.forEach((v,i)=>{if(v>0)sh.push(i)});return ans(sh.length?`The monsoon delay shock runs from <b>${dlab(sh[0])}</b> to <b>${dlab(sh[sh.length-1])}</b> (${sh.length} weeks), followed by a recovery rebound.`:'No monsoon-delay weeks found.',{go:['chan','mon']})}
 if(has(/transfer/)){const n=D.trf.length;return ans(`${fN(n)} depot-to-depot transfers moved ${fN(sum(D.trf.map(r=>r[7])))} units in the history window.`,{go:['supply','trf']})}
 if(has(/capacity|plant|lost sales|allocation/)&&ids){const rows=ids.map(id=>{const N=D.nat[id];return{name:nameOf(id),lb:sum(N.lb2c),l1:sum(N.lp1),l2:sum(N.lp2)}});return ans(`Lost sales by allocation channel (B2C → P1 → P2) for <b>${esc(lab)}</b>.`,{cols:[{k:'name',l:'Product'},{k:'lb',l:'B2C lost',n:1,f:v=>fN(v)},{k:'l1',l:'P1 lost',n:1,f:v=>fN(v)},{k:'l2',l:'P2 lost',n:1,f:v=>fN(v)}],rows,go:['supply','plant']})}
 /* demand totals */
 if(has(/demand|sales|units|volume|sold|how many|total/)){const lw=(nq.match(/last (\d+) weeks/)||[])[1];let i0=0,i1=NH-1;if(lw)i0=NH-(+lw);else if(yr){const ix=W.map((w,i)=>w.startsWith(yr)&&i<NH?i:-1).filter(i=>i>=0);if(ix.length){i0=ix[0];i1=ix[ix.length-1]}}
  const pool=ids||D.prods.map(p=>p.id);const rows=pool.map(id=>{const a=seriesFor(id,lvl,dep,'a'),bu=seriesFor(id,lvl,dep,'bu'),ly=seriesFor(id,lvl,dep,'ly');return{name:nameOf(id),units:sum(a.slice(i0,i1+1)),budget:sum(bu.slice(i0,i1+1)),ly:sum(ly.slice(i0,i1+1))}}).sort((a,b)=>b.units-a.units);const tot=sum(rows.map(r=>r.units));
  return ans(`Demand for <b>${esc(lab)}</b> (${dep?D.dep[dep]:lvl==='K'?'Kolkata':'national'}, ${dlab(i0)} – ${dlab(i1)}): <b>${fN(tot)}</b> units vs budget ${fN(sum(rows.map(r=>r.budget)))}.`,{cols:[{k:'name',l:'Product'},{k:'units',l:'Actual units',n:1,f:v=>fN(v)},{k:'budget',l:'Budget',n:1,f:v=>fN(v)},{k:'ly',l:'Last year',n:1,f:v=>fN(v)}],rows:rows.slice(0,10),go:['forecast']})}
 return null}
return answer}
